name: Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: alpine

    steps:
    - uses: actions/checkout@v4

    - name: mk Release folder
      run: mkdir release

    - name: move files
      run: |
        mv cias release/ &&
        mv gm9 release/ &&
        mv luma release/

    - name: Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: finalize.zip
          body: "finalize"
          draft: false
          prerelease: true